---
# tasks file for install-zeek
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: copy zeek installation files
  copy:
    src: '{{ installation_files }}/zeek'
    dest: '{{ installation_files }}'
    
- name: install zeek 
  command: dpkg -R --install {{ installation_files }}/zeek/
