---
# tasks file for install-haproxy
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: Copy haproxy installation file to the host
  copy:
    src: '{{ installation_files }}/haproxy.deb'
    dest: '{{ installation_files }}/haproxy.deb'
    
- name: install haproxy 
  command: dpkg -i {{ installation_files }}/haproxy.deb
  
- name: systemctl daemon-reload 
  command: systemctl daemon-reload
  
- name: enable haproxy service
  command: systemctl enable haproxy.service