---
# tasks file for install-filebeat
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: Copy filebeat installation file to the host
  copy:
    src: '{{ installation_files }}/filebeat.deb'
    dest: '{{ installation_files }}/filebeat.deb'
    
- name: install filebeat 
  command: dpkg -i {{ installation_files }}/filebeat.deb
  
- name: systemctl daemon-reload 
  command: systemctl daemon-reload
  
- name: enable filebeat service
  command: systemctl enable filebeat.service