---
# tasks file for config-filebeat
- name: stop filebeat service 
  systemd:
    name: filebeat.service
    state: stopped
    
- name: copy filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    
- name: copy filebeat modules zeek
  template:
    src: modules.d/zeek.yml.j2
    dest: /etc/filebeat/modules.d/zeek.yml
    
- name: copy filebeat modules suricata
  template:
    src: modules.d/suricata.yml.j2
    dest: /etc/filebeat/modules.d/suricata.yml
    
- name: copy filebeat modules fortinet
  template:
    src: modules.d/fortinet.yml.j2
    dest: /etc/filebeat/modules.d/fortinet.yml
     
- name: create certs directory
  file:
    path: "/etc/filebeat/certs"
    state: directory
    
- name: copy ca.crt
  copy:
    src: '/elastic-ansible-debian/{{ certificate_path }}/ca/ca.crt'
    dest: '/etc/filebeat/certs/ca.crt'

- name: start filebeat service 
  systemd:
    name: filebeat.service
    state: started    
