---
# tasks file for beats-setup

- name: beats-setup , import beats dashboards
  command: "{{ item }} setup -E setup.kibana.host=https://{{ ansible_host }}.{{ domain_name }}:{{ kibana_port }} -E setup.kibana.username={{ admin_user }} -E setup.kibana.password='{{ admin_password }}' -E setup.kibana.ssl.verification_mode=none -E setup.template.settings.index.number_of_shards= 1 -E output.elasticsearch.hosts=['https://{{ ansible_host }}.{{ domain_name }}:9200'] -E output.elasticsearch.username={{ admin_user }} -E output.elasticsearch.password='{{ admin_password }}'  -E output.elasticsearch.ssl.verification_mode=none -E output.logstash.enabled=false -E setup.template.settings.index.number_of_shards={{ beats_number_of_shards }} -E setup.template.settings.index.number_of_replicas={{ beats_number_of_replicas }} -E setup.template.settings.index.codec={{ beats_codec }} -E setup.template.settings.index.mapping.total_fields.limit= 10000"
  with_items:
    - auditbeat
    - metricbeat
    - filebeat
    - packetbeat
  ignore_errors: yes


