---
- name: stop auditbeat service 
  systemd:
    name: auditbeat.service
    state: stopped
    
- name: copy auditbeat.yml
  template:
    src: auditbeat.yml.j2
    dest: /etc/auditbeat/auditbeat.yml
  
- name: create certs directory
  file:
    path: "/etc/auditbeat/certs"
    state: directory
    
- name: copy ca.crt
  copy:
    src: '/elastic-ansible-debian/{{ certificate_path }}/ca/ca.crt'
    dest: '/etc/auditbeat/certs/ca.crt'

- name: start auditbeat service 
  systemd:
    name: auditbeat.service
    state: started    
