---
# tasks file for install-suricata
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: copy suricata installation files
  copy:
    src: '{{ installation_files }}/suricata'
    dest: '{{ installation_files }}'
    
- name: install suricata 
  command: dpkg -R --install {{ installation_files }}/suricata/