---
# besme allah
# author: ali.ahmadi

- hosts: collector
  become: yes
  tasks:   
  - import_role:
      name: defaults
  - import_role:
      name: promisc-interface
  - import_role:
      name: install-haproxy
  - import_role:
      name: config-haproxy
  - import_role:
      name: install-zeek
  - import_role:
      name: config-zeek
  - import_role:
      name: install-suricata
  - import_role:
      name: config-suricata
  - import_role:
      name: install-rabbitmq
  - import_role:
      name: config-rabbitmq
  - import_role:
      name: install-logstash
  - import_role:
      name: config-logstash-collector
  - import_role:
      name: install-filebeat
  - import_role:
      name: config-filebeat-collector
  - import_role:
      name: install-packetbeat
  - import_role:
      name: config-packetbeat
 