---
# besme allah
# author: ali.ahmadi

- hosts: indexer
  become: yes
  tasks:   
  - import_role:
      name: install-logstash
  - import_role:
      name: install-memcached
  - import_role:
      name: config-logstash-indexer