---
# besme allah
# author: ali.ahmadi

- hosts: collector
  become: yes
  tasks:  
  - import_role:
      name: defaults
  - import_role:
      name: install-rabbitmq
  - import_role:
      name: config-rabbitmq