---
# tasks file for install-metricbeat
- name: Creates directory
  file:
    path: '{{ installation_files }}'
    state: directory  
    
- name: Copy metricbeat installation file to the host
  copy:
    src: '{{ installation_files }}/metricbeat.deb'
    dest: '{{ installation_files }}/metricbeat.deb'
    
- name: install metricbeat 
  command: dpkg -i {{ installation_files }}/metricbeat.deb
  
- name: systemctl daemon-reload 
  command: systemctl daemon-reload
  
- name: enable metricbeat service
  command: systemctl enable metricbeat.service